Transform: 'AWS::Serverless-2016-10-31'
Parameters:
  ApiKeysPrefix:
    Type: String
    Default: apikeys
  TioDomain:
    Type: String
    Default: notconfigured
  TioUsername:
    Type: String
    Default: notconfigured
  TioAccessKey:
    Type: String
    Default: Change Me
    # NoEcho: True
  TioSecretKey:
    Type: String
    Default: Change Me
    # NoEcho: True
  RotationDays:
    Type: Number
    Default: 7

Resources:
  TenableApiKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Tenable API Key
      Tags:
        - Key: tioRole
          Value: Admin
        - Key: tioDomain
          Value: !Sub '${TioDomain}'
        - Key: tioUsername
          Value: !Sub '${TioUsername}'

      SecretString: !Sub '{"accessKey":"${TioAccessKey}","secretKey":"${TioSecretKey}","tioUsername":"${TioUsername}"}'

  ApiKeyRotationSchedule:
    Type: AWS::SecretsManager::RotationSchedule
    Properties:
      RotationLambdaARN: !GetAtt ApiKeyRotationLambda.Arn
      RotationRules:
        AutomaticallyAfterDays: !Sub '${RotationDays}'
      SecretId: !Ref TenableApiKey

  ApiKeyRotationLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: rotate_tenable_keys
      Runtime: python3.9
      Handler: rotate.lambda_handler
      CodeUri: ./app
      Policies:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:DescribeSecret
                - secretsmanager:GetSecretValue
                - secretsmanager:PutSecretValue
                - secretsmanager:UpdateSecretVersionStage
              Resource: 
                - !Ref TenableApiKey
                - arn:aws:secretsmanager:us-east-1:773284714180:secret:apikeys/ag_operator@test.tenable-LMxDcl
            - Effect: Allow
              Action:
                - secretsmanager:ListSecrets
              Resource: '*'

  ApiKeyRotationLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt ApiKeyRotationLambda.Arn
      Action: lambda:InvokeFunction
      Principal: secretsmanager.amazonaws.com